# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc8a221eba652814365393bc6a02118204c6831dc862c81f40e732c2522a22e1f65c0da9cb57eeed43bc94033f11cd13fe5279eacb12d17c844313e2fdbc0aa

test:
  secret_key_base: 17d0f7db056052ed6c40c725b3913b789e967266aa164a2fd780762e5a14f994356582e2a075f71fd1c26387fe96f001c069c8db5e2a15e6d94cc847e2a452d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
